02 javascript data types
js-tasks-ru/js-20210806_alex145 pull request #2
Opened 2021-08-12 19:20 UTC by alex-01010

2021-08-12 19:21 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2021-08-12 19:26 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-08-13 12:23 UTC, dosandk commented on 01-intro/1-sum/index.js
> +  return m + n;
good 👍

2021-08-13 12:23 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    return arrCopy.sort(collator.compare).reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-08-13 12:24 UTC, dosandk requested changes
решение `sortStrings` следует поправить

2021-08-13 14:03 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-08-13 16:24 UTC, dosandk approved these changes
good 👍

2021-08-13 16:24 UTC, merged